#!/bin/bash
const fsExtra = require('fs-extra');
const path = require('path');

const uppercase = process.argv[2];
const kebabcase = uppercase.replace(/([A-Z])/g, '-$1').toLowerCase();

console.log('creating folder');
fsExtra.copySync(path.join('.template', 'api'), path.join('components', kebabcase));
fsExtra.copySync(path.join('.template', 'test'), path.join('tests', 'api', kebabcase));

console.log('modifying files for api');
const componentDir = path.join('components', kebabcase);
fs.readdirSync(componentDir).forEach(file => {
    if (file.includes('(qq)')) {
        let content = fs.readFileSync(path.join(componentDir, file), 'utf8');
        content = content.replace(/\(QQ\)/g, uppercase);
        content = content.replace(/\(qq\)/g, kebabcase);
        fs.writeFileSync(path.join(componentDir, file.replace('(qq)', kebabcase)), content);
    }
});

console.log('modifying files for test');
const testFile = path.join('tests', 'api', kebabcase, 'index.js');
let content = fs.readFileSync(testFile, 'utf8');
content = content.replace(/\(qq\)/g, kebabcase);
fs.writeFileSync(testFile, content);

console.log('process complete');
#         sed -i 's/(QQ)/'$uppercase'/g' "$file"
#         sed -i 's/(qq)/'$kebabcase'/g' "$file"

#         echo '    change' "$file" 'to' `echo "${file//(qq)/$kebabcase}"`
#         mv "$file" `echo "${file//(qq)/$kebabcase}"`
#     done
#     popd >> /dev/null

#     echo 'change' "$D" 'to' `echo "$D"`
#     #change only the last occurence of (qq)
#     mv "$D" `echo "$D"`
# done
ls -al .

echo "modifying files for test"
cd ../../tests/api/$kebabcase
sed -i 's/(qq)/'$kebabcase'/g' "index.js"

echo "process complete"