#!/bin/bash

uppercase=$1
echo $uppercase

kebabcase="$(echo ${uppercase} | sed -e 's/\([A-Z]\)/\-\1/g' -e 's/\-//' | tr '[:upper:]' '[:lower:]')"
echo $kebabcase

echo "creating folder"
cp -R .template/api components/$kebabcase
cp -R .template/test tests/api/$kebabcase

echo "modifying files for api"
cd ./components/$kebabcase

for D in $(find -d . -name "*(qq)*" -type d ) '.' 
do 
    pushd $D >> /dev/null
    echo 'directory: ' "$D"
    for file in $(find . -name "*(qq)*" -type f -maxdepth 1)
    do
        #change variable inside file
        sed -i '' 's/(QQ)/'$uppercase'/g' "$file"
        sed -i '' 's/(qq)/'$kebabcase'/g' "$file"

        echo '    change' "$file" 'to' `echo "${file//(qq)/$kebabcase}"`
        mv "$file" `echo "${file//(qq)/$kebabcase}"`
    done
    popd >> /dev/null

    echo 'change' "$D" 'to' `echo "$D"`
    #change only the last occurence of (qq)
    mv "$D" `echo "$D"`
done
ls -al .

echo "modifying files for test"
cd ../../tests/api/$kebabcase
sed -i '' 's/(qq)/'$kebabcase'/g' "index.js"

echo "process complete"