version: '3'

services:
    express-starter:
      build: .
      ports:
        - 80:${PORT}
      volumes:
        - .:/backend
      depends_on:
        - mongodb
      environment:
        PWD: /backend # no idea why pwd is not working
    mongodb:
      image: mongo:3.6-jessie
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      volumes: 
        - ./data/db:/data/db
      restart: unless-stopped